const affirmations = [
  {
    id: 1,
    affirmation: 'I am capable of achieving great things today.',
    read: false,
  },
  {
    id: 2,
    affirmation: 'Today is a fresh start and a new opportunity.',
    read: false,
  },
  {
    id: 3,
    affirmation: 'I am confident and strong in everything I do.',
    read: false,
  },
  {
    id: 4,
    affirmation: 'I embrace the challenges that come my way.',
    read: false,
  },
  {
    id: 5,
    affirmation: 'I am grateful for the positive things in my life.',
    read: false,
  },
  {
    id: 6,
    affirmation: 'I am focused and determined to succeed.',
    read: false,
  },
  {
    id: 7,
    affirmation: 'I radiate positivity and attract good things.',
    read: false,
  },
  {
    id: 8,
    affirmation: 'I am in control of my thoughts and emotions.',
    read: false,
  },
  {
    id: 9,
    affirmation: 'I have the power to create the life I want.',
    read: false,
  },
  {
    id: 10,
    affirmation: 'I am surrounded by supportive and loving people.',
    read: false,
  },
  {
    id: 11,
    affirmation: 'I am continuously growing and evolving.',
    read: false,
  },
  { id: 12, affirmation: 'I am worthy of love and respect.', read: false },
  { id: 13, affirmation: 'I believe in myself and my abilities.', read: false },
  { id: 14, affirmation: 'I am at peace with who I am.', read: false },
  {
    id: 15,
    affirmation: 'I am deserving of success and happiness.',
    read: false,
  },
  {
    id: 16,
    affirmation: 'I am a positive thinker and only attract positivity.',
    read: false,
  },
  { id: 17, affirmation: 'I am proud of all my achievements.', read: false },
  { id: 18, affirmation: 'I am healthy, wealthy, and happy.', read: false },
  {
    id: 19,
    affirmation: 'I am grateful for another beautiful day.',
    read: false,
  },
  {
    id: 20,
    affirmation: 'I am becoming a better version of myself every day.',
    read: false,
  },
  {
    id: 21,
    affirmation: 'I am surrounded by love and everything is fine.',
    read: false,
  },
  {
    id: 22,
    affirmation: 'I am brimming with energy and overflowing with joy.',
    read: false,
  },
  { id: 23, affirmation: 'I am a magnet for miracles.', read: false },
  { id: 24, affirmation: 'I am resilient, strong, and brave.', read: false },
  {
    id: 25,
    affirmation: 'I am open to new and exciting possibilities.',
    read: false,
  },
  {
    id: 26,
    affirmation: 'I am in charge of how I feel and today I choose happiness.',
    read: false,
  },
  { id: 27, affirmation: 'I am deeply fulfilled with who I am.', read: false },
  {
    id: 28,
    affirmation: 'I am constantly growing and evolving into a better person.',
    read: false,
  },
  {
    id: 29,
    affirmation: 'I am attracting wonderful opportunities into my life.',
    read: false,
  },
  {
    id: 30,
    affirmation: 'I am grateful for the good things in my life.',
    read: false,
  },
  {
    id: 31,
    affirmation: 'I am confident in my abilities and my purpose.',
    read: false,
  },
  { id: 32, affirmation: 'I am surrounded by love and light.', read: false },
  {
    id: 33,
    affirmation: 'I am full of vitality and my mind is calm and peaceful.',
    read: false,
  },
  {
    id: 34,
    affirmation: 'I am a positive thinker and only attract positivity.',
    read: false,
  },
  { id: 35, affirmation: 'I am proud of all my achievements.', read: false },
  { id: 36, affirmation: 'I am healthy, wealthy, and happy.', read: false },
  {
    id: 37,
    affirmation: 'I am grateful for another beautiful day.',
    read: false,
  },
  {
    id: 38,
    affirmation: 'I am becoming a better version of myself every day.',
    read: false,
  },
  {
    id: 39,
    affirmation: 'I am surrounded by love and everything is fine.',
    read: false,
  },
  {
    id: 40,
    affirmation: 'I am brimming with energy and overflowing with joy.',
    read: false,
  },
  { id: 41, affirmation: 'I am a magnet for miracles.', read: false },
  { id: 42, affirmation: 'I am resilient, strong, and brave.', read: false },
  {
    id: 43,
    affirmation: 'I am open to new and exciting possibilities.',
    read: false,
  },
  {
    id: 44,
    affirmation: 'I am in charge of how I feel and today I choose happiness.',
    read: false,
  },
  { id: 45, affirmation: 'I am deeply fulfilled with who I am.', read: false },
  {
    id: 46,
    affirmation: 'I am constantly growing and evolving into a better person.',
    read: false,
  },
  {
    id: 47,
    affirmation: 'I am attracting wonderful opportunities into my life.',
    read: false,
  },
  {
    id: 48,
    affirmation: 'I am grateful for the good things in my life.',
    read: false,
  },
  {
    id: 49,
    affirmation: 'I am confident in my abilities and my purpose.',
    read: false,
  },
  { id: 50, affirmation: 'I am surrounded by love and light.', read: false },
  {
    id: 51,
    affirmation: 'I am full of vitality and my mind is calm and peaceful.',
    read: false,
  },
  {
    id: 52,
    affirmation: 'I am a positive thinker and only attract positivity.',
    read: false,
  },
  { id: 53, affirmation: 'I am proud of all my achievements.', read: false },
  { id: 54, affirmation: 'I am healthy, wealthy, and happy.', read: false },
  {
    id: 55,
    affirmation: 'I am grateful for another beautiful day.',
    read: false,
  },
  {
    id: 56,
    affirmation: 'I am becoming a better version of myself every day.',
    read: false,
  },
  {
    id: 57,
    affirmation: 'I am surrounded by love and everything is fine.',
    read: false,
  },
  {
    id: 58,
    affirmation: 'I am brimming with energy and overflowing with joy.',
    read: false,
  },
  { id: 59, affirmation: 'I am a magnet for miracles.', read: false },
  { id: 60, affirmation: 'I am resilient, strong, and brave.', read: false },
  {
    id: 61,
    affirmation: 'I am open to new and exciting possibilities.',
    read: false,
  },
  {
    id: 62,
    affirmation: 'I am in charge of how I feel and today I choose happiness.',
    read: false,
  },
  { id: 63, affirmation: 'I am deeply fulfilled with who I am.', read: false },
  {
    id: 64,
    affirmation: 'I am constantly growing and evolving into a better person.',
    read: false,
  },
  {
    id: 65,
    affirmation: 'I am attracting wonderful opportunities into my life.',
    read: false,
  },
  {
    id: 66,
    affirmation: 'I am grateful for the good things in my life.',
    read: false,
  },
  {
    id: 67,
    affirmation: 'I am confident in my abilities and my purpose.',
    read: false,
  },
  { id: 68, affirmation: 'I am surrounded by love and light.', read: false },
  {
    id: 69,
    affirmation: 'I am full of vitality and my mind is calm and peaceful.',
    read: false,
  },
  {
    id: 70,
    affirmation: 'I am a positive thinker and only attract positivity.',
    read: false,
  },
  { id: 71, affirmation: 'I am proud of all my achievements.', read: false },
  { id: 72, affirmation: 'I am healthy, wealthy, and happy.', read: false },
  {
    id: 73,
    affirmation: 'I am grateful for another beautiful day.',
    read: false,
  },
  {
    id: 74,
    affirmation: 'I am becoming a better version of myself every day.',
    read: false,
  },
  {
    id: 75,
    affirmation: 'I am surrounded by love and everything is fine.',
    read: false,
  },
  {
    id: 76,
    affirmation: 'I am brimming with energy and overflowing with joy.',
    read: false,
  },
  { id: 77, affirmation: 'I am a magnet for miracles.', read: false },
  { id: 78, affirmation: 'I am resilient, strong, and brave.', read: false },
  {
    id: 79,
    affirmation: 'I am open to new and exciting possibilities.',
    read: false,
  },
  {
    id: 80,
    affirmation: 'I am in charge of how I feel and today I choose happiness.',
    read: false,
  },
  { id: 81, affirmation: 'I am deeply fulfilled with who I am.', read: false },
  {
    id: 82,
    affirmation: 'I am constantly growing and evolving into a better person.',
    read: false,
  },
  {
    id: 83,
    affirmation: 'I am attracting wonderful opportunities into my life.',
    read: false,
  },
  {
    id: 84,
    affirmation: 'I am grateful for the good things in my life.',
    read: false,
  },
  {
    id: 85,
    affirmation: 'I am confident in my abilities and my purpose.',
    read: false,
  },
  { id: 86, affirmation: 'I am surrounded by love and light.', read: false },
  {
    id: 87,
    affirmation: 'I am full of vitality and my mind is calm and peaceful.',
    read: false,
  },
  {
    id: 88,
    affirmation: 'I am a positive thinker and only attract positivity.',
    read: false,
  },
  { id: 89, affirmation: 'I am proud of all my achievements.', read: false },
  { id: 90, affirmation: 'I am healthy, wealthy, and happy.', read: false },
  {
    id: 91,
    affirmation: 'I am grateful for another beautiful day.',
    read: false,
  },
  {
    id: 92,
    affirmation: 'I am becoming a better version of myself every day.',
    read: false,
  },
  {
    id: 93,
    affirmation: 'I am surrounded by love and everything is fine.',
    read: false,
  },
  {
    id: 94,
    affirmation: 'I am brimming with energy and overflowing with joy.',
    read: false,
  },
  { id: 95, affirmation: 'I am a magnet for miracles.', read: false },
  { id: 96, affirmation: 'I am resilient, strong, and brave.', read: false },
  {
    id: 97,
    affirmation: 'I am open to new and exciting possibilities.',
    read: false,
  },
  {
    id: 98,
    affirmation: 'I am in charge of how I feel and today I choose happiness.',
    read: false,
  },
  { id: 99, affirmation: 'I am deeply fulfilled with who I am.', read: false },
  {
    id: 100,
    affirmation: 'I am constantly growing and evolving into a better person.',
    read: false,
  },
  {
    id: 101,
    affirmation: 'I am attracting wonderful opportunities into my life.',
    read: false,
  },
  {
    id: 102,
    affirmation: 'I am grateful for the good things in my life.',
    read: false,
  },
  {
    id: 103,
    affirmation: 'I am confident in my abilities and my purpose.',
    read: false,
  },
  { id: 104, affirmation: 'I am surrounded by love and light.', read: false },
  {
    id: 105,
    affirmation: 'I am full of vitality and my mind is calm and peaceful.',
    read: false,
  },
  {
    id: 106,
    affirmation: 'I am a positive thinker and only attract positivity.',
    read: false,
  },
  { id: 107, affirmation: 'I am proud of all my achievements.', read: false },
  { id: 108, affirmation: 'I am healthy, wealthy, and happy.', read: false },
  {
    id: 109,
    affirmation: 'I am grateful for another beautiful day.',
    read: false,
  },
  {
    id: 110,
    affirmation: 'I am becoming a better version of myself every day.',
    read: false,
  },
  {
    id: 111,
    affirmation: 'I am surrounded by love and everything is fine.',
    read: false,
  },
  {
    id: 112,
    affirmation: 'I am brimming with energy and overflowing with joy.',
    read: false,
  },
  { id: 113, affirmation: 'I am a magnet for miracles.', read: false },
  { id: 114, affirmation: 'I am resilient, strong, and brave.', read: false },
  {
    id: 115,
    affirmation: 'I am open to new and exciting possibilities.',
    read: false,
  },
  {
    id: 116,
    affirmation: 'I am in charge of how I feel and today I choose happiness.',
    read: false,
  },
  { id: 117, affirmation: 'I am deeply fulfilled with who I am.', read: false },
  {
    id: 118,
    affirmation: 'I am constantly growing and evolving into a better person.',
    read: false,
  },
  {
    id: 119,
    affirmation: 'I am attracting wonderful opportunities into my life.',
    read: false,
  },
  {
    id: 120,
    affirmation: 'I am grateful for the good things in my life.',
    read: false,
  },
  {
    id: 121,
    affirmation: 'I am confident in my abilities and my purpose.',
    read: false,
  },
  { id: 122, affirmation: 'I am surrounded by love and light.', read: false },
  {
    id: 123,
    affirmation: 'I am full of vitality and my mind is calm and peaceful.',
    read: false,
  },
  {
    id: 124,
    affirmation: 'I am a positive thinker and only attract positivity.',
    read: false,
  },
  { id: 125, affirmation: 'I am proud of all my achievements.', read: false },
  { id: 126, affirmation: 'I am healthy, wealthy, and happy.', read: false },
  {
    id: 127,
    affirmation: 'I am grateful for another beautiful day.',
    read: false,
  },
  {
    id: 128,
    affirmation: 'I am becoming a better version of myself every day.',
    read: false,
  },
  {
    id: 129,
    affirmation: 'I am surrounded by love and everything is fine.',
    read: false,
  },
  {
    id: 130,
    affirmation: 'I am brimming with energy and overflowing with joy.',
    read: false,
  },
  { id: 131, affirmation: 'I am a magnet for miracles.', read: false },
  { id: 132, affirmation: 'I am resilient, strong, and brave.', read: false },
  {
    id: 133,
    affirmation: 'I am open to new and exciting possibilities.',
    read: false,
  },
  {
    id: 134,
    affirmation: 'I am in charge of how I feel and today I choose happiness.',
    read: false,
  },
  { id: 135, affirmation: 'I am deeply fulfilled with who I am.', read: false },
  {
    id: 136,
    affirmation: 'I am constantly growing and evolving into a better person.',
    read: false,
  },
  {
    id: 137,
    affirmation: 'I am attracting wonderful opportunities into my life.',
    read: false,
  },
  {
    id: 138,
    affirmation: 'I am grateful for the good things in my life.',
    read: false,
  },
  {
    id: 139,
    affirmation: 'I am confident in my abilities and my purpose.',
    read: false,
  },
  { id: 140, affirmation: 'I am surrounded by love and light.', read: false },
  {
    id: 141,
    affirmation: 'I am full of vitality and my mind is calm and peaceful.',
    read: false,
  },
  {
    id: 142,
    affirmation: 'I am a positive thinker and only attract positivity.',
    read: false,
  },
  { id: 143, affirmation: 'I am proud of all my achievements.', read: false },
  { id: 144, affirmation: 'I am healthy, wealthy, and happy.', read: false },
  {
    id: 145,
    affirmation: 'I am grateful for another beautiful day.',
    read: false,
  },
  {
    id: 146,
    affirmation: 'I am becoming a better version of myself every day.',
    read: false,
  },
  {
    id: 147,
    affirmation: 'I am surrounded by love and everything is fine.',
    read: false,
  },
  {
    id: 148,
    affirmation: 'I am brimming with energy and overflowing with joy.',
    read: false,
  },
  { id: 149, affirmation: 'I am a magnet for miracles.', read: false },
  { id: 150, affirmation: 'I am resilient, strong, and brave.', read: false },
  {
    id: 151,
    affirmation: 'I am open to new and exciting possibilities.',
    read: false,
  },
  {
    id: 152,
    affirmation: 'I am in charge of how I feel and today I choose happiness.',
    read: false,
  },
  { id: 153, affirmation: 'I am deeply fulfilled with who I am.', read: false },
  {
    id: 154,
    affirmation: 'I am constantly growing and evolving into a better person.',
    read: false,
  },
  {
    id: 155,
    affirmation: 'I am attracting wonderful opportunities into my life.',
    read: false,
  },
  {
    id: 156,
    affirmation: 'I am grateful for the good things in my life.',
    read: false,
  },
  {
    id: 157,
    affirmation: 'I am confident in my abilities and my purpose.',
    read: false,
  },
  { id: 158, affirmation: 'I am surrounded by love and light.', read: false },
  {
    id: 159,
    affirmation: 'I am full of vitality and my mind is calm and peaceful.',
    read: false,
  },
  {
    id: 160,
    affirmation: 'I am a positive thinker and only attract positivity.',
    read: false,
  },
  { id: 161, affirmation: 'I am proud of all my achievements.', read: false },
  { id: 162, affirmation: 'I am healthy, wealthy, and happy.', read: false },
  {
    id: 163,
    affirmation: 'I am grateful for another beautiful day.',
    read: false,
  },
  {
    id: 164,
    affirmation: 'I am becoming a better version of myself every day.',
    read: false,
  },
  {
    id: 165,
    affirmation: 'I am surrounded by love and everything is fine.',
    read: false,
  },
  {
    id: 166,
    affirmation: 'I am brimming with energy and overflowing with joy.',
    read: false,
  },
  { id: 167, affirmation: 'I am a magnet for miracles.', read: false },
  { id: 168, affirmation: 'I am resilient, strong, and brave.', read: false },
  {
    id: 169,
    affirmation: 'I am open to new and exciting possibilities.',
    read: false,
  },
  {
    id: 170,
    affirmation: 'I am in charge of how I feel and today I choose happiness.',
    read: false,
  },
  { id: 171, affirmation: 'I am deeply fulfilled with who I am.', read: false },
  {
    id: 172,
    affirmation: 'I am constantly growing and evolving into a better person.',
    read: false,
  },
  {
    id: 173,
    affirmation: 'I am attracting wonderful opportunities into my life.',
    read: false,
  },
  {
    id: 174,
    affirmation: 'I am grateful for the good things in my life.',
    read: false,
  },
  {
    id: 175,
    affirmation: 'I am confident in my abilities and my purpose.',
    read: false,
  },
  { id: 176, affirmation: 'I am surrounded by love and light.', read: false },
  {
    id: 177,
    affirmation: 'I am full of vitality and my mind is calm and peaceful.',
    read: false,
  },
  {
    id: 178,
    affirmation: 'I am a positive thinker and only attract positivity.',
    read: false,
  },
  { id: 179, affirmation: 'I am proud of all my achievements.', read: false },
  { id: 180, affirmation: 'I am healthy, wealthy, and happy.', read: false },
  {
    id: 181,
    affirmation: 'I am grateful for another beautiful day.',
    read: false,
  },
  {
    id: 182,
    affirmation: 'I am becoming a better version of myself every day.',
    read: false,
  },
  {
    id: 183,
    affirmation: 'I am surrounded by love and everything is fine.',
    read: false,
  },
  {
    id: 184,
    affirmation: 'I am brimming with energy and overflowing with joy.',
    read: false,
  },
  { id: 185, affirmation: 'I am a magnet for miracles.', read: false },
  { id: 186, affirmation: 'I am resilient, strong, and brave.', read: false },
  {
    id: 187,
    affirmation: 'I am open to new and exciting possibilities.',
    read: false,
  },
  {
    id: 188,
    affirmation: 'I am in charge of how I feel and today I choose happiness.',
    read: false,
  },
  { id: 189, affirmation: 'I am deeply fulfilled with who I am.', read: false },
  {
    id: 190,
    affirmation: 'I am constantly growing and evolving into a better person.',
    read: false,
  },
  {
    id: 191,
    affirmation: 'I am attracting wonderful opportunities into my life.',
    read: false,
  },
  {
    id: 192,
    affirmation: 'I am grateful for the good things in my life.',
    read: false,
  },
  {
    id: 193,
    affirmation: 'I am confident in my abilities and my purpose.',
    read: false,
  },
  { id: 194, affirmation: 'I am surrounded by love and light.', read: false },
  {
    id: 195,
    affirmation: 'I am full of vitality and my mind is calm and peaceful.',
    read: false,
  },
  {
    id: 196,
    affirmation: 'I am a positive thinker and only attract positivity.',
    read: false,
  },
  { id: 197, affirmation: 'I am proud of all my achievements.', read: false },
  { id: 198, affirmation: 'I am healthy, wealthy, and happy.', read: false },
  {
    id: 199,
    affirmation: 'I am grateful for another beautiful day.',
    read: false,
  },
  {
    id: 200,
    affirmation: 'I am becoming a better version of myself every day.',
    read: false,
  },
  {
    id: 201,
    affirmation: 'I am surrounded by love and everything is fine.',
    read: false,
  },
  {
    id: 202,
    affirmation: 'I am brimming with energy and overflowing with joy.',
    read: false,
  },
  { id: 203, affirmation: 'I am a magnet for miracles.', read: false },
  { id: 204, affirmation: 'I am resilient, strong, and brave.', read: false },
  {
    id: 205,
    affirmation: 'I am open to new and exciting possibilities.',
    read: false,
  },
  {
    id: 206,
    affirmation: 'I am in charge of how I feel and today I choose happiness.',
    read: false,
  },
  { id: 207, affirmation: 'I am deeply fulfilled with who I am.', read: false },
  {
    id: 208,
    affirmation: 'I am constantly growing and evolving into a better person.',
    read: false,
  },
  {
    id: 209,
    affirmation: 'I am attracting wonderful opportunities into my life.',
    read: false,
  },
  {
    id: 210,
    affirmation: 'I am grateful for the good things in my life.',
    read: false,
  },
  {
    id: 211,
    affirmation: 'I am confident in my abilities and my purpose.',
    read: false,
  },
  { id: 212, affirmation: 'I am surrounded by love and light.', read: false },
  {
    id: 213,
    affirmation: 'I am full of vitality and my mind is calm and peaceful.',
    read: false,
  },
  {
    id: 214,
    affirmation: 'I am a positive thinker and only attract positivity.',
    read: false,
  },
  { id: 215, affirmation: 'I am proud of all my achievements.', read: false },
  { id: 216, affirmation: 'I am healthy, wealthy, and happy.', read: false },
  {
    id: 217,
    affirmation: 'I am grateful for another beautiful day.',
    read: false,
  },
  {
    id: 218,
    affirmation: 'I am becoming a better version of myself every day.',
    read: false,
  },
  {
    id: 219,
    affirmation: 'I am surrounded by love and everything is fine.',
    read: false,
  },
  {
    id: 220,
    affirmation: 'I am brimming with energy and overflowing with joy.',
    read: false,
  },
  { id: 221, affirmation: 'I am a magnet for miracles.', read: false },
  { id: 222, affirmation: 'I am resilient, strong, and brave.', read: false },
  {
    id: 223,
    affirmation: 'I am open to new and exciting possibilities.',
    read: false,
  },
  {
    id: 224,
    affirmation: 'I am in charge of how I feel and today I choose happiness.',
    read: false,
  },
  { id: 225, affirmation: 'I am deeply fulfilled with who I am.', read: false },
  {
    id: 226,
    affirmation: 'I am constantly growing and evolving into a better person.',
    read: false,
  },
  {
    id: 227,
    affirmation: 'I am attracting wonderful opportunities into my life.',
    read: false,
  },
  {
    id: 228,
    affirmation: 'I am grateful for the good things in my life.',
    read: false,
  },
  {
    id: 229,
    affirmation: 'I am confident in my abilities and my purpose.',
    read: false,
  },
  { id: 230, affirmation: 'I am surrounded by love and light.', read: false },
  {
    id: 231,
    affirmation: 'I am full of vitality and my mind is calm and peaceful.',
    read: false,
  },
  {
    id: 232,
    affirmation: 'I am a positive thinker and only attract positivity.',
    read: false,
  },
  { id: 233, affirmation: 'I am proud of all my achievements.', read: false },
  { id: 234, affirmation: 'I am healthy, wealthy, and happy.', read: false },
  {
    id: 235,
    affirmation: 'I am grateful for another beautiful day.',
    read: false,
  },
  {
    id: 236,
    affirmation: 'I am becoming a better version of myself every day.',
    read: false,
  },
  {
    id: 237,
    affirmation: 'I am surrounded by love and everything is fine.',
    read: false,
  },
  {
    id: 238,
    affirmation: 'I am brimming with energy and overflowing with joy.',
    read: false,
  },
  { id: 239, affirmation: 'I am a magnet for miracles.', read: false },
  { id: 240, affirmation: 'I am resilient, strong, and brave.', read: false },
  {
    id: 241,
    affirmation: 'I am open to new and exciting possibilities.',
    read: false,
  },
  {
    id: 242,
    affirmation: 'I am in charge of how I feel and today I choose happiness.',
    read: false,
  },
  { id: 243, affirmation: 'I am deeply fulfilled with who I am.', read: false },
  {
    id: 244,
    affirmation: 'I am constantly growing and evolving into a better person.',
    read: false,
  },
  {
    id: 245,
    affirmation: 'I am attracting wonderful opportunities into my life.',
    read: false,
  },
  {
    id: 246,
    affirmation: 'I am grateful for the good things in my life.',
    read: false,
  },
  {
    id: 247,
    affirmation: 'I am confident in my abilities and my purpose.',
    read: false,
  },
  { id: 248, affirmation: 'I am surrounded by love and light.', read: false },
  {
    id: 249,
    affirmation: 'I am full of vitality and my mind is calm and peaceful.',
    read: false,
  },
  {
    id: 250,
    affirmation: 'I am a positive thinker and only attract positivity.',
    read: false,
  },
  { id: 251, affirmation: 'I am proud of all my achievements.', read: false },
  { id: 252, affirmation: 'I am healthy, wealthy, and happy.', read: false },
  {
    id: 253,
    affirmation: 'I am grateful for another beautiful day.',
    read: false,
  },
  {
    id: 254,
    affirmation: 'I am becoming a better version of myself every day.',
    read: false,
  },
  {
    id: 255,
    affirmation: 'I am surrounded by love and everything is fine.',
    read: false,
  },
  {
    id: 256,
    affirmation: 'I am brimming with energy and overflowing with joy.',
    read: false,
  },
  { id: 257, affirmation: 'I am a magnet for miracles.', read: false },
  { id: 258, affirmation: 'I am resilient, strong, and brave.', read: false },
  {
    id: 259,
    affirmation: 'I am open to new and exciting possibilities.',
    read: false,
  },
  {
    id: 260,
    affirmation: 'I am in charge of how I feel and today I choose happiness.',
    read: false,
  },
  { id: 261, affirmation: 'I am deeply fulfilled with who I am.', read: false },
  {
    id: 262,
    affirmation: 'I am constantly growing and evolving into a better person.',
    read: false,
  },
  {
    id: 263,
    affirmation: 'I am attracting wonderful opportunities into my life.',
    read: false,
  },
  {
    id: 264,
    affirmation: 'I am grateful for the good things in my life.',
    read: false,
  },
  {
    id: 265,
    affirmation: 'I am confident in my abilities and my purpose.',
    read: false,
  },
  { id: 266, affirmation: 'I am surrounded by love and light.', read: false },
  {
    id: 267,
    affirmation: 'I am full of vitality and my mind is calm and peaceful.',
    read: false,
  },
  {
    id: 268,
    affirmation: 'I am a positive thinker and only attract positivity.',
    read: false,
  },
  { id: 269, affirmation: 'I am proud of all my achievements.', read: false },
  { id: 270, affirmation: 'I am healthy, wealthy, and happy.', read: false },
  {
    id: 271,
    affirmation: 'I am grateful for another beautiful day.',
    read: false,
  },
  {
    id: 272,
    affirmation: 'I am becoming a better version of myself every day.',
    read: false,
  },
  {
    id: 273,
    affirmation: 'I am surrounded by love and everything is fine.',
    read: false,
  },
  {
    id: 274,
    affirmation: 'I am brimming with energy and overflowing with joy.',
    read: false,
  },
  { id: 275, affirmation: 'I am a magnet for miracles.', read: false },
  { id: 276, affirmation: 'I am resilient, strong, and brave.', read: false },
  {
    id: 277,
    affirmation: 'I am open to new and exciting possibilities.',
    read: false,
  },
  {
    id: 278,
    affirmation: 'I am in charge of how I feel and today I choose happiness.',
    read: false,
  },
  { id: 279, affirmation: 'I am deeply fulfilled with who I am.', read: false },
  {
    id: 280,
    affirmation: 'I am constantly growing and evolving into a better person.',
    read: false,
  },
  {
    id: 281,
    affirmation: 'I am attracting wonderful opportunities into my life.',
    read: false,
  },
  {
    id: 282,
    affirmation: 'I am grateful for the good things in my life.',
    read: false,
  },
  {
    id: 283,
    affirmation: 'I am confident in my abilities and my purpose.',
    read: false,
  },
  { id: 284, affirmation: 'I am surrounded by love and light.', read: false },
  {
    id: 285,
    affirmation: 'I am full of vitality and my mind is calm and peaceful.',
    read: false,
  },
  {
    id: 286,
    affirmation: 'I am a positive thinker and only attract positivity.',
    read: false,
  },
  { id: 287, affirmation: 'I am proud of all my achievements.', read: false },
  { id: 288, affirmation: 'I am healthy, wealthy, and happy.', read: false },
  {
    id: 289,
    affirmation: 'I am grateful for another beautiful day.',
    read: false,
  },
  {
    id: 290,
    affirmation: 'I am becoming a better version of myself every day.',
    read: false,
  },
  {
    id: 291,
    affirmation: 'I am surrounded by love and everything is fine.',
    read: false,
  },
  {
    id: 292,
    affirmation: 'I am brimming with energy and overflowing with joy.',
    read: false,
  },
  { id: 293, affirmation: 'I am a magnet for miracles.', read: false },
  { id: 294, affirmation: 'I am resilient, strong, and brave.', read: false },
  {
    id: 295,
    affirmation: 'I am open to new and exciting possibilities.',
    read: false,
  },
  {
    id: 296,
    affirmation: 'I am in charge of how I feel and today I choose happiness.',
    read: false,
  },
  { id: 297, affirmation: 'I am deeply fulfilled with who I am.', read: false },
  {
    id: 298,
    affirmation: 'I am constantly growing and evolving into a better person.',
    read: false,
  },
  {
    id: 299,
    affirmation: 'I am attracting wonderful opportunities into my life.',
    read: false,
  },
  {
    id: 300,
    affirmation: 'I am grateful for the good things in my life.',
    read: false,
  },
  {
    id: 301,
    affirmation: 'I am confident in my abilities and my purpose.',
    read: false,
  },
  { id: 302, affirmation: 'I am surrounded by love and light.', read: false },
  {
    id: 303,
    affirmation: 'I am full of vitality and my mind is calm and peaceful.',
    read: false,
  },
  {
    id: 304,
    affirmation: 'I am a positive thinker and only attract positivity.',
    read: false,
  },
  { id: 305, affirmation: 'I am proud of all my achievements.', read: false },
  { id: 306, affirmation: 'I am healthy, wealthy, and happy.', read: false },
  {
    id: 307,
    affirmation: 'I am grateful for another beautiful day.',
    read: false,
  },
  {
    id: 308,
    affirmation: 'I am becoming a better version of myself every day.',
    read: false,
  },
  {
    id: 309,
    affirmation: 'I am surrounded by love and everything is fine.',
    read: false,
  },
  {
    id: 310,
    affirmation: 'I am brimming with energy and overflowing with joy.',
    read: false,
  },
  { id: 311, affirmation: 'I am a magnet for miracles.', read: false },
  { id: 312, affirmation: 'I am resilient, strong, and brave.', read: false },
  {
    id: 313,
    affirmation: 'I am open to new and exciting possibilities.',
    read: false,
  },
  {
    id: 314,
    affirmation: 'I am in charge of how I feel and today I choose happiness.',
    read: false,
  },
  { id: 315, affirmation: 'I am deeply fulfilled with who I am.', read: false },
  {
    id: 316,
    affirmation: 'I am constantly growing and evolving into a better person.',
    read: false,
  },
  {
    id: 317,
    affirmation: 'I am attracting wonderful opportunities into my life.',
    read: false,
  },
  {
    id: 318,
    affirmation: 'I am grateful for the good things in my life.',
    read: false,
  },
  {
    id: 319,
    affirmation: 'I am confident in my abilities and my purpose.',
    read: false,
  },
  { id: 320, affirmation: 'I am surrounded by love and light.', read: false },
  {
    id: 321,
    affirmation: 'I am full of vitality and my mind is calm and peaceful.',
    read: false,
  },
  {
    id: 322,
    affirmation: 'I am a positive thinker and only attract positivity.',
    read: false,
  },
  { id: 323, affirmation: 'I am proud of all my achievements.', read: false },
  { id: 324, affirmation: 'I am healthy, wealthy, and happy.', read: false },
  {
    id: 325,
    affirmation: 'I am grateful for another beautiful day.',
    read: false,
  },
  {
    id: 326,
    affirmation: 'I am becoming a better version of myself every day.',
    read: false,
  },
  {
    id: 327,
    affirmation: 'I am surrounded by love and everything is fine.',
    read: false,
  },
  {
    id: 328,
    affirmation: 'I am brimming with energy and overflowing with joy.',
    read: false,
  },
  { id: 329, affirmation: 'I am a magnet for miracles.', read: false },
  { id: 330, affirmation: 'I am resilient, strong, and brave.', read: false },
  {
    id: 331,
    affirmation: 'I am open to new and exciting possibilities.',
    read: false,
  },
  {
    id: 332,
    affirmation: 'I am in charge of how I feel and today I choose happiness.',
    read: false,
  },
  { id: 333, affirmation: 'I am deeply fulfilled with who I am.', read: false },
  {
    id: 334,
    affirmation: 'I am constantly growing and evolving into a better person.',
    read: false,
  },
  {
    id: 335,
    affirmation: 'I am attracting wonderful opportunities into my life.',
    read: false,
  },
  {
    id: 336,
    affirmation: 'I am grateful for the good things in my life.',
    read: false,
  },
  {
    id: 337,
    affirmation: 'I am confident in my abilities and my purpose.',
    read: false,
  },
  { id: 338, affirmation: 'I am surrounded by love and light.', read: false },
  {
    id: 339,
    affirmation: 'I am full of vitality and my mind is calm and peaceful.',
    read: false,
  },
  {
    id: 340,
    affirmation: 'I am a positive thinker and only attract positivity.',
    read: false,
  },
  { id: 341, affirmation: 'I am proud of all my achievements.', read: false },
  { id: 342, affirmation: 'I am healthy, wealthy, and happy.', read: false },
  {
    id: 343,
    affirmation: 'I am grateful for another beautiful day.',
    read: false,
  },
  {
    id: 344,
    affirmation: 'I am becoming a better version of myself every day.',
    read: false,
  },
  {
    id: 345,
    affirmation: 'I am surrounded by love and everything is fine.',
    read: false,
  },
  {
    id: 346,
    affirmation: 'I am brimming with energy and overflowing with joy.',
    read: false,
  },
  { id: 347, affirmation: 'I am a magnet for miracles.', read: false },
  { id: 348, affirmation: 'I am resilient, strong, and brave.', read: false },
  {
    id: 349,
    affirmation: 'I am open to new and exciting possibilities.',
    read: false,
  },
  {
    id: 350,
    affirmation: 'I am in charge of how I feel and today I choose happiness.',
    read: false,
  },
  { id: 351, affirmation: 'I am deeply fulfilled with who I am.', read: false },
  {
    id: 352,
    affirmation: 'I am constantly growing and evolving into a better person.',
    read: false,
  },
  {
    id: 353,
    affirmation: 'I am attracting wonderful opportunities into my life.',
    read: false,
  },
  {
    id: 354,
    affirmation: 'I am grateful for the good things in my life.',
    read: false,
  },
  {
    id: 355,
    affirmation: 'I am confident in my abilities and my purpose.',
    read: false,
  },
  { id: 356, affirmation: 'I am surrounded by love and light.', read: false },
  {
    id: 357,
    affirmation: 'I am full of vitality and my mind is calm and peaceful.',
    read: false,
  },
  {
    id: 358,
    affirmation: 'I am a positive thinker and only attract positivity.',
    read: false,
  },
  { id: 359, affirmation: 'I am proud of all my achievements.', read: false },
  { id: 360, affirmation: 'I am healthy, wealthy, and happy.', read: false },
  {
    id: 361,
    affirmation: 'I am grateful for another beautiful day.',
    read: false,
  },
  {
    id: 362,
    affirmation: 'I am becoming a better version of myself every day.',
    read: false,
  },
  {
    id: 363,
    affirmation: 'I am surrounded by love and everything is fine.',
    read: false,
  },
  {
    id: 364,
    affirmation: 'I am brimming with energy and overflowing with joy.',
    read: false,
  },
  { id: 365, affirmation: 'I am a magnet for miracles.', read: false },
  { id: 366, affirmation: 'I am resilient, strong, and brave.', read: false },
  {
    id: 367,
    affirmation: 'I am open to new and exciting possibilities.',
    read: false,
  },
  {
    id: 368,
    affirmation: 'I am in charge of how I feel and today I choose happiness.',
    read: false,
  },
  { id: 369, affirmation: 'I am deeply fulfilled with who I am.', read: false },
  {
    id: 370,
    affirmation: 'I am constantly growing and evolving into a better person.',
    read: false,
  },
  {
    id: 371,
    affirmation: 'I am attracting wonderful opportunities into my life.',
    read: false,
  },
  {
    id: 372,
    affirmation: 'I am grateful for the good things in my life.',
    read: false,
  },
  {
    id: 373,
    affirmation: 'I am confident in my abilities and my purpose.',
    read: false,
  },
  { id: 374, affirmation: 'I am surrounded by love and light.', read: false },
  {
    id: 375,
    affirmation: 'I am full of vitality and my mind is calm and peaceful.',
    read: false,
  },
  {
    id: 376,
    affirmation: 'I am a positive thinker and only attract positivity.',
    read: false,
  },
  { id: 377, affirmation: 'I am proud of all my achievements.', read: false },
  { id: 378, affirmation: 'I am healthy, wealthy, and happy.', read: false },
  {
    id: 379,
    affirmation: 'I am grateful for another beautiful day.',
    read: false,
  },
  {
    id: 380,
    affirmation: 'I am becoming a better version of myself every day.',
    read: false,
  },
  {
    id: 381,
    affirmation: 'I am surrounded by love and everything is fine.',
    read: false,
  },
  {
    id: 382,
    affirmation: 'I am brimming with energy and overflowing with joy.',
    read: false,
  },
  { id: 383, affirmation: 'I am a magnet for miracles.', read: false },
  { id: 384, affirmation: 'I am resilient, strong, and brave.', read: false },
  {
    id: 385,
    affirmation: 'I am open to new and exciting possibilities.',
    read: false,
  },
  {
    id: 386,
    affirmation: 'I am in charge of how I feel and today I choose happiness.',
    read: false,
  },
  { id: 387, affirmation: 'I am deeply fulfilled with who I am.', read: false },
  {
    id: 388,
    affirmation: 'I am constantly growing and evolving into a better person.',
    read: false,
  },
  {
    id: 389,
    affirmation: 'I am attracting wonderful opportunities into my life.',
    read: false,
  },
  {
    id: 390,
    affirmation: 'I am grateful for the good things in my life.',
    read: false,
  },
  {
    id: 391,
    affirmation: 'I am confident in my abilities and my purpose.',
    read: false,
  },
  { id: 392, affirmation: 'I am surrounded by love and light.', read: false },
  {
    id: 393,
    affirmation: 'I am full of vitality and my mind is calm and peaceful.',
    read: false,
  },
  {
    id: 394,
    affirmation: 'I am a positive thinker and only attract positivity.',
    read: false,
  },
  { id: 395, affirmation: 'I am proud of all my achievements.', read: false },
  { id: 396, affirmation: 'I am healthy, wealthy, and happy.', read: false },
  {
    id: 397,
    affirmation: 'I am grateful for another beautiful day.',
    read: false,
  },
  {
    id: 398,
    affirmation: 'I am becoming a better version of myself every day.',
    read: false,
  },
  {
    id: 399,
    affirmation: 'I am surrounded by love and everything is fine.',
    read: false,
  },
  {
    id: 400,
    affirmation: 'I am brimming with energy and overflowing with joy.',
    read: false,
  },
  { id: 401, affirmation: 'I am a magnet for miracles.', read: false },
  { id: 402, affirmation: 'I am resilient, strong, and brave.', read: false },
  {
    id: 403,
    affirmation: 'I am open to new and exciting possibilities.',
    read: false,
  },
  {
    id: 404,
    affirmation: 'I am in charge of how I feel and today I choose happiness.',
    read: false,
  },
  { id: 405, affirmation: 'I am deeply fulfilled with who I am.', read: false },
  {
    id: 406,
    affirmation: 'I am constantly growing and evolving into a better person.',
    read: false,
  },
  {
    id: 407,
    affirmation: 'I am attracting wonderful opportunities into my life.',
    read: false,
  },
  {
    id: 408,
    affirmation: 'I am grateful for the good things in my life.',
    read: false,
  },
  {
    id: 409,
    affirmation: 'I am confident in my abilities and my purpose.',
    read: false,
  },
  { id: 410, affirmation: 'I am surrounded by love and light.', read: false },
  {
    id: 411,
    affirmation: 'I am full of vitality and my mind is calm and peaceful.',
    read: false,
  },
  {
    id: 412,
    affirmation: 'I am a positive thinker and only attract positivity.',
    read: false,
  },
  { id: 413, affirmation: 'I am proud of all my achievements.', read: false },
  { id: 414, affirmation: 'I am healthy, wealthy, and happy.', read: false },
  {
    id: 415,
    affirmation: 'I am grateful for another beautiful day.',
    read: false,
  },
  {
    id: 416,
    affirmation: 'I am becoming a better version of myself every day.',
    read: false,
  },
  {
    id: 417,
    affirmation: 'I am surrounded by love and everything is fine.',
    read: false,
  },
  {
    id: 418,
    affirmation: 'I am brimming with energy and overflowing with joy.',
    read: false,
  },
  { id: 419, affirmation: 'I am a magnet for miracles.', read: false },
  { id: 420, affirmation: 'I am resilient, strong, and brave.', read: false },
  {
    id: 421,
    affirmation: 'I am open to new and exciting possibilities.',
    read: false,
  },
  {
    id: 422,
    affirmation: 'I am in charge of how I feel and today I choose happiness.',
    read: false,
  },
  { id: 423, affirmation: 'I am deeply fulfilled with who I am.', read: false },
  {
    id: 424,
    affirmation: 'I am constantly growing and evolving into a better person.',
    read: false,
  },
  {
    id: 425,
    affirmation: 'I am attracting wonderful opportunities into my life.',
    read: false,
  },
  {
    id: 426,
    affirmation: 'I am grateful for the good things in my life.',
    read: false,
  },
  {
    id: 427,
    affirmation: 'I am confident in my abilities and my purpose.',
    read: false,
  },
  { id: 428, affirmation: 'I am surrounded by love and light.', read: false },
];

export default affirmations;
